spring:
  data:
    mongodb:
      uri: mongodb://localhost/security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/bns
          jwk-set-uri: http://localhost:9090/realms/bns/protocol/openid-connect/certs
          auth:
            converter:
              resource-id: sandbox-application
              principle-attribute: preferred_username
jwt:
  auth:
    converter:
      resource-id: sandbox-application
      principle-attribute: preferred_username
