spring:
  data:
    mongodb:
      uri: mongodb://localhost/security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/book-social-network
          jwk-set-uri: http://localhost:9090/realms/book-social-network/protocol/openid-connect/certs
          auth:
            converter:
              resource-id: bsn
              principle-attribute: preferred_username
jwt:
  auth:
    converter:
      resource-id: bsn
      principle-attribute: preferred_username
